### ISSUE TITLE
Will not install on Rasbian Jessie with node version 8.1.2

### ISSUE THREAD

**Issue by ZiCog** [joeferner/node-pi-watchdog#2]
I tried to install pi-watchdog on Raspbian Jessie with node 8.1.2 and it failed. The end of the error messages is shown below.

$ npm install pi-watchdog
...
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uin                                                     t32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Lo                                                     cal<v8::String>, const v8::ScriptOrigin&)’:
../node_modules/nan/nan.h:806:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCo                                                     mpiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::Compil                                                     eOptions)’ is deprecated (declared at /home/rsm/.node-gyp/8.1.2/include/node/v8.h:132                                                     1): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Lo                                                     cal<v8::String>)’:
../node_modules/nan/nan.h:813:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCo                                                     mpiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::Compil                                                     eOptions)’ is deprecated (declared at /home/rsm/.node-gyp/8.1.2/include/node/v8.h:132                                                     1): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
ioctl.target.mk:93: recipe for target 'Release/obj.target/ioctl/src/ioctl.o' failed
make: *** [Release/obj.target/ioctl/src/ioctl.o] Error 1
make: Leaving directory '/home/rsm/flir/node_modules/ioctl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rsm/.nvm/versions/node/v8.1.2/lib/no                                                     de_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:                                                     197:12)
gyp ERR! System Linux 4.9.24-v7+
gyp ERR! command "/home/rsm/.nvm/versions/node/v8.1.2/bin/node" "/home/rsm/.nvm/versi                                                     ons/node/v8.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rsm/flir/node_modules/ioctl
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN flir@1.0.0 No repository field.
npm WARN flir@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ioctl@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ioctl@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging                                                      output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rsm/.npm/_logs/2017-06-20T01_55_36_808Z-debug.log

**Comment by AntoineFootbar** [comment]
Hi ZiCog,
I'm facing the same issue, did you succeed to install pi-watchdog on your Pi ? Thanks in advance.
